Createroute
WildCodeSchool/2103-lille-js-p3-edtech-backend pull request #1
Opened 2021-06-02 19:51 UTC by Hacene010

2021-06-02 20:30 UTC, GeorgesFORTRY approved these changes
Good job ! 👍

2021-06-03 05:49 UTC, LoicBrassart requested changes
One silly evil

2021-06-03 05:49 UTC, LoicBrassart commented on index.js
> +      console.log(results);
No `console.log` in production

2021-06-03 05:49 UTC, LoicBrassart commented on data/db.sql
> +-- MySQL dump 10.13  Distrib 8.0.25, for Linux (x86_64)
The vuerd file generated by the VSC plugin generates a clunky database structure, I'll recreate it myself today. For now it's okay, but we'll replace this file quickly

2021-06-03 09:52 UTC, GeorgesFORTRY approved these changes
it's ok despite additional changes

2021-06-04 10:44 UTC, LoicBrassart requested changes
One more Evil

2021-06-04 10:44 UTC, LoicBrassart commented on package.json
> +    "start": "nodemon index.js",
Oh noes, absolutely not! >_<
Why: `nodemon` is a dev dependancy, but the `npm run start` will be executed on the production machine (where `nodemon` will be absent), you should not do this
Alternative: you could create a "dev" script to run the website with `nodemon` if you want

2021-06-04 11:12 UTC, GeorgesFORTRY approved these changes
ok !

2021-06-04 11:46 UTC, LoicBrassart approved these changes
No more Evils!

2021-06-04 13:59 UTC, merged