improvement of the delete / users route
WildCodeSchool/2103-lille-js-p3-edtech-backend pull request #33
Opened 2021-07-19 14:57 UTC by GeorgesFORTRY

2021-07-19 18:36 UTC, Hacene010 approved these changes
good job

2021-07-20 06:50 UTC, LoicBrassart requested changes
One little fix to do

2021-07-20 06:50 UTC, LoicBrassart commented on routes/auth.js
> +      res.status(500).send('Error deleting an user');
Send one of these codes instead:
409 (Conflict)
405 (Method not Allowed)
I'd say 405 may be an overkill, but in this case the 409 code seems legit : because of one of your system's rules, you don't want to remove the last administrator

2021-07-20 13:30 UTC, LoicBrassart approved these changes
SnE

2021-07-20 14:28 UTC, merged