backend for the map
WildCodeSchool/2103-lille-js-p3-edtech-backend pull request #5
Opened 2021-06-09 12:05 UTC by ThaiBangHOANG

Hello,
I have just added the database for the map part on the backend.
Thank you very much for your verification and validation.

2021-06-09 13:56 UTC, GeorgesFORTRY approved these changes
OK but no react in backend

2021-06-09 13:56 UTC, GeorgesFORTRY commented on package.json
> +    "react-router-dom": "^5.2.0"
useless in backend

2021-06-09 14:08 UTC, LoicBrassart requested changes

2021-06-09 14:08 UTC, LoicBrassart commented on package.json
> +    "react-router-dom": "^5.2.0"
Totally, yep
So I wonder why you validated the PR, @GeorgesFORTRY ? :p

2021-06-09 14:22 UTC, ThaiBangHOANG commented on package.json
> +    "react-router-dom": "^5.2.0"
I did not know why react has installed in the backend as well :p

2021-06-09 14:26 UTC, GeorgesFORTRY approved these changes
ok 😥

2021-06-11 08:58 UTC, LoicBrassart approved these changes
Much better

2021-06-11 09:00 UTC, merged