Slider
WildCodeSchool/2103-lille-js-p3-edtech-backend pull request #6
Opened 2021-06-09 13:55 UTC by yulen59

2021-06-09 14:07 UTC, GeorgesFORTRY approved these changes
ok

2021-06-11 08:55 UTC, LoicBrassart requested changes
One asynchronous Evil

2021-06-11 08:55 UTC, LoicBrassart commented on index.js
> +app.get('/slider', async (req, res) => {
Either you use `async` **and** `await`, or use classic callbacks

2021-06-11 08:55 UTC, LoicBrassart commented on index.js
>  app.get('/members', async (req, res) => {
I see that I let it slide beforehand, please fix it everywhere

2021-06-14 08:13 UTC, GeorgesFORTRY approved these changes
ok

2021-06-14 09:35 UTC, LoicBrassart approved these changes
SnE!

2021-06-14 09:35 UTC, merged